# Generated by Django 3.2.3 on 2021-05-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinehub_backend', '0002_auto_20210528_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='running_movie',
            name='occupied_seats',
        ),
    ]
