# Generated by Django 3.2.3 on 2021-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinehub_backend', '0004_auto_20210528_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
