# Generated by Django 3.2.3 on 2021-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinehub_backend', '0006_alter_movie_language'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='running_movie',
            name='unique_movie_hall',
        ),
        migrations.AddConstraint(
            model_name='running_movie',
            constraint=models.UniqueConstraint(fields=('running_id', 'movie_id', 'hall_id'), name='unique_movie_hall'),
        ),
    ]
